#ifndef INCLUDES_H
# define INCLUDES_H

//libft
#include "tests_ft_isalpha.c"
#include "tests_ft_isdigit.c"
#include "tests_ft_isalnum.c"
#include "tests_ft_isascii.c"
#include "tests_ft_isprint.c"
#include "tests_ft_strlen.c"
#include "tests_ft_memset.c"
#include "tests_ft_bzero.c"
#include "tests_ft_memcpy.c"
#include "tests_ft_memmove.c"
#include "tests_ft_strlcpy.c"
#include "tests_ft_strlcat.c"
#include "tests_ft_toupper.c"
#include "tests_ft_tolower.c"
#include "tests_ft_strchr.c"
#include "tests_ft_strrchr.c"
#include "tests_ft_strncmp.c"
#include "tests_ft_memchr.c"
#include "tests_ft_memcmp.c"
#include "tests_ft_strnstr.c"
#include "tests_ft_atoi.c"
#include "tests_ft_calloc.c"
#include "tests_ft_strdup.c"
#include "tests_ft_substr.c"
#include "tests_ft_strjoin.c"
#include "tests_ft_strtrim.c"
#include "tests_ft_split.c"
#include "tests_ft_itoa.c"
#include "tests_ft_strmapi.c"
#include "tests_ft_striteri.c"
#include "tests_ft_putchar_fd.c"
#include "tests_ft_putstr_fd.c"
#include "tests_ft_putendl_fd.c"
#include "tests_ft_putnbr_fd.c"
//bonus
#include "tests_ft_lstnew.c"
#include "tests_ft_lstadd_front.c"
#include "tests_ft_lstsize.c"
#include "tests_ft_lstlast.c"
#include "tests_ft_lstadd_back.c"
#include "tests_ft_lstdelone.c"
#include "tests_ft_lstclear.c"
#include "tests_ft_lstiter.c"
#include "tests_ft_lstmap.c"
//gnl
#include "tests_get_next_line.c"
//printf
#include "tests_ft_printf.c"
#include "tests_ft_printf_c_and_%.c"
#include "tests_ft_printf_d_and_i.c"
#include "tests_ft_printf_p.c"
#include "tests_ft_printf_s.c"
#include "tests_ft_printf_u.c"
#include "tests_ft_printf_x_and_X.c"
//additional
#include "tests_ft_isspace.c"
#include "tests_ft_atol.c"
#include "tests_ft_strjoin3.c"
#include "tests_ft_atoi_base.c"
#include "tests_ft_word_count.c"

#endif
